version: '3.9'

services:
  traefik:
    container_name: traefik
    image: traefik:v2.9
    restart: always
    ports:
      - 80:80
      - 443:443
    networks:
      - web
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik.yaml:/etc/traefik/traefik.yaml




  mygov1:
    container_name: mygov1
    # A container that exposes an API to show its IP address
    image: yudady/mygo:v1
    deploy:
      replicas: 3
    networks:
      - web
    labels:
      - "traefik.http.routers.mygov1.rule=Host(`mygov1.docker.localhost`)"


  mygov2:
    container_name: mygov2
    # A container that exposes an API to show its IP address
    image: yudady/mygo:v2
    deploy:
      replicas: 3
    networks:
      - web
    labels:
      - "traefik.http.routers.mygov2.rule=Host(`mygov2.docker.localhost`)"




networks:
  web:
    external: true

# 需要修有 web network
# $ docker network create web
# curl -H Host:mygov1.docker.localhost http://127.0.0.1
# curl -H Host:mygov2.docker.localhost http://127.0.0.1