version: '3.8'

services:
  bind:
    container_name: bind
    image: yudady/bind
    build:
      context: .
    restart: always
    ports:
    - "53:53/udp"
    - "53:53/tcp"
    - "10000:10000/tcp"
    volumes:
    - ./data:/data
