apiVersion: skaffold/v3
kind: Config
metadata:
  name: BLOG

#################################################

build:
  local:
    push: false # don't push on Docker Hub
    useDockerCLI: true
  # something that needs to be maintained
  artifacts:
    - image: yudady/client # rebuild entire image if below sync files are not matched
      context: client # watch for changes in this dir
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
            - src: "src/**/*.js" # when js file is changed, copy it to the Pod
              dest: .
    - image: yudady/comments
      context: comments
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "src/**/*.js" # when js file is changed, copy it to the Pod
            dest: .
    - image: yudady/event-bus
      context: event-bus
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "src/**/*.js" # when js file is changed, copy it to the Pod
            dest: .
    - image: yudady/moderation
      context: moderation
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "src/**/*.js" # when js file is changed, copy it to the Pod
            dest: .
    - image: yudady/posts
      context: posts
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "src/**/*.js" # when js file is changed, copy it to the Pod
            dest: .
    - image: yudady/query
      context: query
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "src/**/*.js" # when js file is changed, copy it to the Pod
            dest: .

#################################################
manifests:
  rawYaml:
    - ./infra/k8s/*


#################################################

deploy:
  kubectl:
    flags:
      disableValidation: true
  kubeContext: minikube
  logs:
    prefix: podAndContainer

#################################################

profiles:
  - name: blog
    activation:
      - command: dev
      - kubeContext: minikube
