apiVersion: apps/v1
kind: Deployment
metadata:
  name: maven
spec:
  selector:
    matchLabels:
      app: maven
  template:
    metadata:
      labels:
        app: maven
    spec:
      containers:
      - name: maven
        image: yudady/maven
        ports:
          - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: maven
spec:
  ports:
    - port: 8080
      name: http
  type: ClusterIP
  selector:
    app: maven