
image:
  file: .gitpod.Dockerfile
tasks:
  - init: |
      chmod a+w /var/run/docker.sock && 
      make build-linux
github:
  prebuilds:
    master: true
    branches: true
    pullRequests: true
    pullRequestsFromForks: true
    addCheck: true
vscode:
  extensions:
    - ms-azuretools.vscode-docker
