version: '3.8'

services:
  paketobuildpacks:
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - ..:/workspace:cached
      - ${HOME}/.m2:/home/cnb/.m2:rw
    command: sleep infinity