version: '3.8'

services:
  paketobuildpacks:
    user: root
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - ..:/workspace:cached
      - ~/.m2:/root/.m2:rw
      - ~/.gradle:/root/.gradle:rw
    command: sleep infinity