apiVersion: apps/v1
kind: Deployment
metadata:
  name: gradle
spec:
  selector:
    matchLabels:
      app: gradle
  template:
    metadata:
      labels:
        app: gradle
    spec:
      containers:
      - name: gradle
        image: yudady/gradle
        ports:
          - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: gradle
spec:
  ports:
    - port: 8080
      name: http
  type: ClusterIP
  selector:
    app: gradle